### ISSUE TITLE
Option to have a GIF "still" with no play/pause button

### ISSUE THREAD

**Issue by gcamacho079** [adamchaboryk/gifa11y#3]
Hi, I'm looking to implement something like this on a project. However, it would be useful to have the option to show just the still, with no ability to play or pause.

This would be useful for certain scenarios, like when a small preview thumbnail of the GIF is shown, where the ability to play the GIF might be overkill.

Thanks!

**Comment by adamchaboryk** [comment]
Hi @gcamacho079,

Sorry for the super slow reply, but I finally got around to updating Gifa11y! I added a new boolean prop `showButtons`. If you use it in combination with `initiallyPaused` you should be able to achieve your scenario. 

Cheers!
