### ISSUE TITLE
Real Pause

### ISSUE THREAD

**Issue by skerbis** [adamchaboryk/gifa11y#6]
At the moment, the first image is displayed when paused (or so it seems to me). Would it be possible to show the current frame?

**Comment by adamchaboryk** [comment]
Hi @skerbis, showing the current frame is a lot more complex (which is out of scope for this library). The closest library to achieve that would be this older library created by [Buzzfeed called libgif.js](https://github.com/buzzfeed/libgif-js)

**Comment by skerbis** [comment]
thx
